name: Deploy to App Engine

on:
  push:
    branches: ['main']
    paths:
      - 'api/**'
      - 'client/**'
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add authentication at the start of build job
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Create config directory and file
      - name: Setup config
        run: |
          mkdir -p config
          cat > config/librechat.yaml << EOF
          version: 1.0.5
          cache: true
          EOF
          cp config/librechat.yaml librechat.yaml

      - name: Create app.yaml
        run: |
          cat > app.yaml << EOF
          runtime: custom
          env: flex

          manual_scaling:
            instances: 1
            
          resources:
            cpu: 2
            memory_gb: 4
            disk_size_gb: 20
            
          network:
            session_affinity: true
            forwarded_ports:
              - 80:3080
            
          env_variables:
            NODE_ENV: "production"
            HOST: "0.0.0.0"
            PORT: "3080"

          volumes:
            - name: librechat-config
              size_gb: 1
              mount_point: "/app/librechat.yaml"
            - name: librechat-data
              size_gb: 10
              mount_point: "/app/client/public/images"
            - name: librechat-logs
              size_gb: 5
              mount_point: "/app/api/logs"
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker us.gcr.io --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: us.gcr.io/${{ env.PROJECT_ID }}/librechat:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          deliverables: app.yaml
          image_url: us.gcr.io/${{ env.PROJECT_ID }}/librechat:${{ github.sha }}
